version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules    
    networks:
      - internal
      - external

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - internal

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  redis-data:
